# This is a basic workflow to help you get started with Actions

name: Check Markdown links

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
